
spring:
  application:
    name: blog


  datasource:
    url: jdbc:h2:mem:blog
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: ALWAYS